AwsS3Test/Models/PreSignRequest.cs
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace TraniningMVC.Models
{
    public enum BucketRegion
    {
        USEast2,
        USEast1,
        CACentral1,
        CNNorthWest,
        CNNorth1,
        USGovCloudWest1,
        SAEast1,
        APSoutheast1,
        APSouth1,
        APNortheast2,
        APSoutheast2,
        EUCentral1,
        EUWest3,
        EUWest2,
        EUWest1,
        USWest2,
        USWest1,
        APNortheast1
    }

    public class PreSignedRequest
    {
        [HiddenInput(DisplayValue = false)]
        public RegionEndpoint BucketRegion { get; set; }

        [DisplayName("Region")]
        public BucketRegion BucketRegionEnum { get; set; } = Models.BucketRegion.USEast2;

        [DisplayName("Bucket name")]
        public string BucketName { get; set; } = "test-bucket-pre-sign-url";

        [DisplayName("Object Key")]
        public string ObjectKey { get; set; } = "default";

        public HttpPostedFileBase File { get; set; }

        [Range(0, 3, ErrorMessage = "Select a correct license")]
        public HttpVerb HttpRequestMethod { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayName("Expiration time")]
        public DateTime ExpirationTime { get; set; }

        private static IAmazonS3 s3Client;

        public string SendRequest()
        {
            var bucketRegion = typeof(RegionEndpoint).GetField(BucketRegionEnum.ToString()).GetValue(null);
            s3Client = new AmazonS3Client((RegionEndpoint)bucketRegion);
            var url = GeneratePreSignedURL();

            HttpWebRequest httpRequest = WebRequest.Create(url) as HttpWebRequest;
            httpRequest.Method = HttpRequestMethod.ToString();

            if (HttpRequestMethod == HttpVerb.PUT)
            {
                AddFile(httpRequest, url);
            }

            HttpWebResponse response = httpRequest.GetResponse() as HttpWebResponse;

            return url;
        }

        private void AddFile(HttpWebRequest httpRequest, string url)
        {
            using (Stream dataStream = httpRequest.GetRequestStream())
            {
                File.InputStream.CopyTo(dataStream);
            }
        }

        private string GeneratePreSignedURL()
        {
            var request = new GetPreSignedUrlRequest
            {
                BucketName = BucketName,
                Key = ObjectKey,
                Verb = HttpRequestMethod,
                Expires = ExpirationTime
            };

            string url = s3Client.GetPreSignedURL(request);
            return url;
        }
    }
}

AwsS3Test/Models/PreSignedRequest.cs
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace TraniningMVC.Models
{
    public enum BucketRegion
    {
        USEast2,
        USEast1,
        CACentral1,
        CNNorthWest,
        CNNorth1,
        USGovCloudWest1,
        SAEast1,
        APSoutheast1,
        APSouth1,
        APNortheast2,
        APSoutheast2,
        EUCentral1,
        EUWest3,
        EUWest2,
        EUWest1,
        USWest2,
        USWest1,
        APNortheast1
    }

    public class PreSignedRequest
    {
        [HiddenInput(DisplayValue = false)]
        public RegionEndpoint BucketRegion { get; set; }

        [DisplayName("Region")]
        public BucketRegion BucketRegionEnum { get; set; } = Models.BucketRegion.USEast2;

        [DisplayName("Bucket name")]
        public string BucketName { get; set; } = "test-bucket-pre-sign-url";

        [DisplayName("Object Key")]
        public string ObjectKey { get; set; } = Guid.NewGuid().ToString() + ".zip";

        public HttpPostedFileBase File { get; set; }

        [Range(0, 3, ErrorMessage = "Select a correct license")]
        public HttpVerb HttpRequestMethod { get; set; } = HttpVerb.PUT;

        [DataType(DataType.DateTime)]
        [DisplayName("Expiration time")]
        public DateTime ExpirationTime { get; set; }

        private static IAmazonS3 s3Client;

        public string SendRequest()
        {
            var bucketRegion = typeof(RegionEndpoint).GetField(BucketRegionEnum.ToString()).GetValue(null);
            s3Client = new AmazonS3Client((RegionEndpoint)bucketRegion);
            var url = GeneratePreSignedURL();

            HttpWebRequest httpRequest = WebRequest.Create(url) as HttpWebRequest;
            httpRequest.Method = HttpRequestMethod.ToString();

            if (HttpRequestMethod == HttpVerb.PUT)
            {
                AddFile(httpRequest, url);
            }

            HttpWebResponse response = httpRequest.GetResponse() as HttpWebResponse;

            return url;
        }

        private void AddFile(HttpWebRequest httpRequest, string url)
        {
            using (Stream dataStream = httpRequest.GetRequestStream())
            {
                File.InputStream.CopyTo(dataStream);
            }
        }

        private string GeneratePreSignedURL()
        {
            var request = new GetPreSignedUrlRequest
            {
                BucketName = BucketName,
                Key = ObjectKey,
                Verb = HttpRequestMethod,
                Expires = ExpirationTime
            };

            string url = s3Client.GetPreSignedURL(request);
            return url;
        }
    }
}

AwsS3Test/Models/PreSignedUrlData.cs
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AwsS3Test.Models
{
    public class PreSignedUrlData
    {
        public string ObjectKey { get; set; }
        public string BucketName { get; set; }
        public string BucketRegion { get; set; }

        public string GeneratePreSignedURL()
        {
            var bucketRegion = typeof(RegionEndpoint).GetField(BucketRegion).GetValue(null);
            var s3Client = new AmazonS3Client((RegionEndpoint)bucketRegion);

            var request = new GetPreSignedUrlRequest
            {
                BucketName = BucketName,
                Key = ObjectKey,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddHours(1)
            };

            string url = s3Client.GetPreSignedURL(request);
            return url;
        }
    }
}

AwsS3Test/Controllers/AwsBucketController.cs
using AwsS3Test.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TraniningMVC.Models;

namespace TraniningMVC.Controllers
{
    public class AwsBucketController : Controller
    {
        [HttpGet]
        public ActionResult Test()
        {
            return View(new PreSignedRequest());
        }
        
        [HttpPost]
        public ActionResult Test(PreSignedRequest preSignRequest)
        {
            var result = preSignRequest.SendRequest();
            return Redirect(result);
        }

        [HttpPost]
        public JsonResult GeneratePreSignedUrl(PreSignedUrlData data)
        {
            return Json(data.GeneratePreSignedURL());
        }
    }
}

AwsS3Test/Views/AwsBucket/Test.cshtml
@using Amazon
@using Amazon.S3
@model TraniningMVC.Models.PreSignedRequest

@{
    ViewBag.Title = "Test";
}

<div class="conroller-urls">
    <div id="GeneratePreSignedUrl" data-request-url="@Url.Action("GeneratePreSignedUrl", "AwsBucket")"></div>
</div>

<h2>AWS S3 SDK test</h2>


@*@using (Html.BeginForm("Test", "AwsBucket", FormMethod.Post, new { enctype = "multipart/form-data" }))
{*@
<div class="form-horizontal">
    <h4>Pre-signed request</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BucketRegionEnum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" id="bucket-region">
            @Html.DisplayFor(model => model.BucketRegionEnum, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BucketRegionEnum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BucketName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" id="bucket-name">
            @Html.DisplayFor(model => model.BucketName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BucketName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ObjectKey, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" id="object-key">
            @Html.DisplayFor(model => model.ObjectKey, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ObjectKey, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group file-upload">
        @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.File, new { @type = "file", style = "width: 50%" })
            @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value=@Model.HttpRequestMethod class="btn btn-default" onclick="sendFileToTheBucket()" />
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/awsBucket/Test.js")
}

AwsS3Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AWS S3 SDK Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AWS S3 SDK Test</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>